server.port: 9086

auth:
  app:
    jwtSecret: ASecretOfADude
    jwtExpirationMs: 86400000
    header_string: Authorization


# --------------
# MONGODB settings
# --------------
# Database name.
spring.data.mongodb.database: programmer-dev
spring.data.mongodb.host: 192.168.0.18
# Mongo server port. Cannot be set with URI
spring.data.mongodb.port: 27017
# Login user of the mongo server. Cannot be set with URI
spring.data.mongodb.username: root
# Login password of the mongo server. Cannot be set with URI.
spring.data.mongodb.password: example #fh3022480db
spring.data.mongodb.authentication-database: admin



